# Generated by Django 4.0.4 on 2023-06-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('college1', models.CharField(max_length=100)),
                ('college2', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('place', models.CharField(max_length=100)),
            ],
        ),
    ]
